#port setting
server:
  port: 9000

#jsp setting
spring:
# 포워드를 jsp에서 tiles로 변경했으므로 주석처리
#  mvc:
#    view:
#      prefix: /WEB-INF/
#      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


#gangsa mysql db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-n9jk3-kr.vpc-pub-cdb.ntruss.com:3306/pp?serverTimezone=Asia/Seoul
    username: study
    password: bitcamp!@#123


##mysql bit701
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/pp?serverTimezone=Asia/Seoul
#    username: root
#    password: 35373537

#mybatis setting
mybatis:
  type-aliases-package: data.dto
  mapper-locations:
  - /mapper/**/*.xml